server:
  port: 4001
  max-http-request-header-size: 64KB

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Note: jwk-set-uri is set below in jwt.* section for split issuer support
          issuer-uri: http://keycloak:8080/realms/fortressbank-realm

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://account-service-db:5432/accountdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

# JWT Configuration for split issuer support
# - jwk-set-uri: Where to fetch public keys (Docker-internal Keycloak URL)
# - expected-issuer: What issuer to expect in tokens (external URL that clients use)
# This is needed because KC_HOSTNAME=localhost makes tokens have issuer=localhost:8888
# but Docker services need to fetch keys from fortressbank-keycloak:8080
jwt:
  jwk-set-uri: http://fortressbank-keycloak:8080/realms/fortressbank-realm/protocol/openid-connect/certs
  expected-issuer: http://localhost:8888/realms/fortressbank-realm