# Local development profile - overrides Docker hostnames
spring:
  config:
    import: optional:configserver:http://localhost:8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
