# Local development profile - overrides Docker hostnames
spring:
  # Risk engine is stateless, doesn't need database
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
