server:
  port: 4000
  max-http-request-header-size: 64KB

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Note: jwk-set-uri is set below in jwt.* section for split issuer support
          jwk-set-uri: http://keycloak:8080/realms/fortressbank-realm/protocol/openid-connect/certs

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://user-service-db:5432/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 60000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest

  # Email Configuration - SendGrid
  mail:
    host: ${MAIL_HOST:smtp.sendgrid.net}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:apikey}
    password: ${MAIL_PASSWORD} # SendGrid API Key
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# JWT Configuration for split issuer support
# - jwk-set-uri: Where to fetch public keys (Docker-internal Keycloak URL)
# - expected-issuer: What issuer to expect in tokens (external URL that clients use)
# This is needed because KC_HOSTNAME=localhost makes tokens have issuer=localhost:8888
# but Docker services need to fetch keys from fortressbank-keycloak:8080
jwt:
  jwk-set-uri: http://fortressbank-keycloak:8080/realms/fortressbank-realm/protocol/openid-connect/certs
  expected-issuer: http://localhost:8888/realms/fortressbank-realm

# Custom Email Configuration
fortress-bank:
  email:
    from: ${EMAIL_FROM} # Must be verified sender email
    from-name: ${EMAIL_FROM_NAME:Fortress Bank}
    otp:
      subject: "Your OTP Code - Fortress Bank"
      expiry-minutes: 5

  ai-service:
    url: http://host.docker.internal:5000
# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
