# Local development profile - overrides Docker hostnames
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8888/realms/fortressbank-realm/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: postgres
    password: "123456"

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Email Configuration - disabled for local dev (use MailHog or similar if needed)
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Custom Email Configuration - dummy values for local dev
fortress-bank:
  email:
    from: noreply@fortressbank.local
    from-name: Fortress Bank (Local)
    otp:
      subject: "Your OTP Code - Fortress Bank"
      expiry-minutes: 5
  ai-service:
    url: http://localhost:5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: http://localhost:8888
